[tool.poetry]
name = "gignore-cli"
version = "1.1.6"
description = "A simple CLI for quickly generating .gitignore files from gitignore.io templates"
authors = ["ze-fernando <zefernando.dev@gmail.com>"]
readme = "README.md"
license = "MIT"
packages = [{ include = "gignore", from = "src" }]


[tool.poetry.dependencies]
python = "==3.14.*"
httpx2 = ">=2.13.0"
rich = ">=15.0.0"

[tool.poetry.scripts]
gignore = "gignore.main:run"

[tool.poe]
poetry_command = ""

[tool.poe.tasks]
dev = "python src/gignore/main.py"
